debug: false

spring:
  profiles:
    active: dev
  config:
    location: classpath
  # mysql数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.cherrycc.com:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      initial-size: 1
      max-wait: 60000
  # redis
  redis:
    database: 0
    host: www.cherrycc.com
    port: 6379
    password:
    timeout: 1000
    # 连接池
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0

  # 国际化
  messages:
    basename: i18n.msg
  # 前端模板
  thymeleaf:
    cache: false

#实体类扫描包
mybatis:
  # 配置Mapper.xml中使用(resultType、parameterType)实体的路径
  typeAliasesPackage: com.less.dao.entity
  # Mapper.xml文件扫描目录
  mapperLocations: classpath:mapper/*.xml
  # 驼峰命名
  configuration:
    mapUnderscoreToCamelCase: true
    lazy-loading-enabled: true
    cache-enabled: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

dubbo:
  application:
    name: user-consumer
  registry:
    address: www.cherrycc.com:2181
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: registry
  consumer:
    check: false
    timeout: 3000

---
# 产品环境
server:
  port: 8088
  servlet:
    context-path: /
spring:
  profiles: prod
---
# 开发环境
server:
  port: 8088
  servlet:
    context-path: /
spring:
  profiles: dev