server:
  port: 8087
dubbo:
  application:
    name: user-provider
  registry:
    address: www.cherrycc.com:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: registry
